import type { Metadata } from 'next'
import { ThemeProvider } from "@/components/theme-provider"
import "./global.css"
import { ClerkProvider } from '@clerk/nextjs'
import CourseContextProvider from './contexts/chosencourse-context'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
    <head />
    <body>
      <ClerkProvider>
        <CourseContextProvider>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        {children}
      </ThemeProvider>

        </CourseContextProvider>
      </ClerkProvider>
      
    </body>
  </html>
  )
}
