import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import "./global.css";
import { ClerkProvider } from "@clerk/nextjs";
import CourseContextProvider from "./contexts/chosencourse-context";
import ChosenCourseContextProvider from "./contexts/chosen-course-data";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ClerkProvider>
          <Providers>
            <ChosenCourseContextProvider>
              <CourseContextProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
                >
                  <Navbar />
                  {children}
                  <Toaster />
                </ThemeProvider>
              </CourseContextProvider>
            </ChosenCourseContextProvider>
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
